# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85d81ca75a2bdf3a25fc922037fe25a7f1b512aa958a78bde679606404227e126be7ea39e3a7ebdb79d8f2b528c5c3727c67f78409de9df0f7d3c6fcebb9143b

test:
  secret_key_base: 048fc00292e7dbeb0124feeec323709488976fad3aa88f903ba790e415b6c1569ba3585ddf36062205374053b136d7ee4bfa569dc668970a1a1969642851a939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
